### ISSUE TITLE
Test with Kubernetes

### ISSUE THREAD

**Issue by tadam98** [wingedrasengan927/Tensorflow-2-Object-Detection-API-Flask-Application#3]
Hi,

The correction to the docker helped.
I deployed to kuberebetes per your instructions. Instanth looks healthy:
gke-object-detection-default-pool-147a6724-0kt9      us-central1-a   n1-standard-4                               10.128.15.228  130.211.230.217  RUNNING
gke-object-detection-default-pool-147a6724-rr7s      us-central1-a   n1-standard-4                               10.128.15.231  35.222.253.157   RUNNING

it appears to be running but not responding (I tried IP addresses of both nodes. Also both answer ping).

[]($ python client.py --address http://35.224.180.205:5000 --image_path images/girl_image.jpg --output_dir outputs/
Traceback (most recent call last):
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb8d9dbc3d0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='35.224.180.205', port=5000): Max retries exceeded with url: /object_detection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8d9dbc3d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 47, in <module>
    response = post_image(args.image_path, url)
  File "client.py", line 30, in post_image
    response = requests.post(URL, data=img, headers=headers)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/mickey/.conda/envs/blurmvp2.2a/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='35.224.180.205', port=5000): Max retries exceeded with url: /object_detection (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb8d9dbc3d0>: Failed to establish a new connection: [Errno 110] Connection timed out')))

**Comment by wingedrasengan927** [comment]
Hey Mickey,
In the article, I exposed port 80 on the load balancer.
So you should run:
`python client.py --address http://35.224.180.205:80 --image_path images/girl_image.jpg --output_dir outputs/`
instead of 5000.

**Comment by tadam98** [comment]
Then, kindly correct the article :) 
Only one link works.

$ python client.py --address http://130.211.230.217:80 --image_path images/girl_image.jpg --output_dir outputs
Error:  connection refused
$ python client.py --address http://35.224.180.205:80 --image_path images/girl_image.jpg --output_dir outputs/
detections are:  [{'person': '79%'}, {'chair': '34%'}]
the image size is:  size=1920x1281
the image is being written in outputs/

**Comment by tadam98** [comment]
Also, I am not sure how the "two node cluster" comes into use. I see one image processed throuh the load balancer and an answer returned.

**Comment by wingedrasengan927** [comment]
Hey Mickey,
I think the first address is of the cluster-ID, and hence it is not working.

The two-node cluster will help in scalability in case there are multiple clients.
The Kubernetes load balancer will take care of that.

Sorry for the article,
Will update it to add more detailed explanations and recent developments soon.
and Thanks for bringing it to my notice.

Closing this issue.
